-- MySQL Script generated by MySQL Workbench
-- Fri Nov  5 00:58:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sgpdrat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgpdrat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgpdrat` DEFAULT CHARACTER SET utf8 ;
USE `sgpdrat` ;

-- -----------------------------------------------------
-- Table `sgpdrat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpdrat`.`users` (
  `id` INT(11) NOT NULL,
  `nombreUsuario` VARCHAR(16) NOT NULL,
  `contrasena` VARCHAR(32) NOT NULL,
  `rol` VARCHAR(16) NOT NULL,
  `nombre` VARCHAR(256) NOT NULL,
  `cedula` VARCHAR(9) NOT NULL,
  `telefono` VARCHAR(16) NOT NULL,
  `correo` VARCHAR(128) NOT NULL,
  `remember_token` VARCHAR(128) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgpdrat`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpdrat`.`proyecto` (
  `id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `numero_contratacion` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `objetivo` VARCHAR(1024) NOT NULL,
  `ubicacion` VARCHAR(256) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_final` DATETIME NOT NULL,
  `forma_pago` VARCHAR(32) NOT NULL,
  `monto_adjudicado` DOUBLE(10,2) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Proyecto_Usuario_idx` (`user_id` ASC) ,
  CONSTRAINT `FK_Proyecto_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `sgpdrat`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgpdrat`.`inspeccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpdrat`.`inspeccion` (
  `id` INT(11) NOT NULL,
  `proyecto_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `numero` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `observaciones` VARCHAR(4096) NULL DEFAULT NULL,
  `firma` VARCHAR(128) NULL DEFAULT NULL,
  `avance_obra` DOUBLE(2,2) NOT NULL,
  `procentaje_pagado` DOUBLE(2,2) NOT NULL,
  `tareas_ejecutadas` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Inspeccion_Proyecto_idx` (`proyecto_id` ASC) ,
  INDEX `FK_Inspeccion_Usuario_idx` (`user_id` ASC) ,
  CONSTRAINT `FK_Inspeccion_Proyecto`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `sgpdrat`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Inspeccion_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `sgpdrat`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgpdrat`.`archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpdrat`.`archivos` (
  `id` INT(11) NOT NULL,
  `inspeccion_id` INT(11) NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Adjuntos_Inspeccion_idx` (`inspeccion_id` ASC) ,
  CONSTRAINT `FK_Archivos_Inspeccion`
    FOREIGN KEY (`inspeccion_id`)
    REFERENCES `sgpdrat`.`inspeccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgpdrat`.`cronograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpdrat`.`cronograma` (
  `id` INT(11) NOT NULL,
  `proyecto_id` INT(11) NOT NULL,
  `Cronogramacol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Cronograma_Proyecto_idx` (`proyecto_id` ASC) ,
  CONSTRAINT `FK_Cronograma_Proyecto`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `sgpdrat`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgpdrat`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpdrat`.`fotos` (
  `id` INT(11) NOT NULL,
  `inspeccion_id` INT(11) NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Fotos_Inspeccion_idx` (`inspeccion_id` ASC) ,
  CONSTRAINT `FK_Fotos_Inspeccion`
    FOREIGN KEY (`inspeccion_id`)
    REFERENCES `sgpdrat`.`inspeccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgpdrat`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpdrat`.`pago` (
  `id` INT(11) NOT NULL,
  `proyecto_id` INT(11) NOT NULL,
  `numero` INT(11) NOT NULL,
  `proyeccion` DOUBLE(10,2) NOT NULL,
  `monto` DOUBLE(10,2) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Pago_Proyecto_idx` (`proyecto_id` ASC) ,
  CONSTRAINT `FK_Pago_Proyecto`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `sgpdrat`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgpdrat`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgpdrat`.`tarea` (
  `id` INT(11) NOT NULL,
  `proyecto_id` INT(11) NOT NULL,
  `numero` INT(11) NOT NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  `peso` DOUBLE(2,2) NOT NULL,
  `avance` DOUBLE(2,2) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Tarea_Proyecto_idx` (`proyecto_id` ASC) ,
  CONSTRAINT `FK_Tarea_Proyecto`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `sgpdrat`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
